### PR TITLE
Add German translation

### PR DESCRIPTION
**Pull request by psjnek**

### CODE REVIEW

**Comment by WebSnke** [comment]
@SuperrSonic Could you take a look at my pull request?

**Comment by SuperrSonic** [comment]
My bad for skipping this, I sort of took a break from this stuff.

Because WiiMC needs as much memory as possible, I looked at many ways to free up some space, language files are all incomplete because there are less options now (no youtube quality, no theme selection from settings, etc.) but also new options like deflicker, and tiled rendering (called 'enhanced resolution') I decided to take out all the language files I could not provide with a complete translation.

If you can add the missing strings, I can add this back. I would also like to say that I just updated recently, so it may be some time before I compile this again. In the meantime, you might be able to hex edit the Spanish file in the boot.dol if you need the language working now.

**Comment by WebSnke** [comment]
> My bad for skipping this, I sort of took a break from this stuff.
> 
> Because WiiMC needs as much memory as possible, I looked at many ways to free up some space, language files are all incomplete because there are less options now (no youtube quality, no theme selection from settings, etc.) but also new options like deflicker, and tiled rendering (called 'enhanced resolution') I decided to take out all the language files I could not provide with a complete translation.
> 
> If you can add the missing strings, I can add this back. I would also like to say that I just updated recently, so it may be some time before I compile this again. In the meantime, you might be able to hex edit the Spanish file in the boot.dol if you need the language working now.

Sorry, I don't really get what I am supposed to do now. What do you mean by "add the missing strings"?

**Comment by SuperrSonic** [comment]
There's new text to translate, and also text that has been removed. The current translation files contain all those unused strings, wasting memory.

There's no ideal way to find which strings are missing or no longer needed, you would have to compare with the current translations available.

**Comment by WebSnke** [comment]
> There's new text to translate, and also text that has been removed. The current translation files contain all those unused strings, wasting memory.
> 
> There's no ideal way to find which strings are missing or no longer needed, you would have to compare with the current translations available.

So where can I find the new strings?

**Pull request closed without merging**
